get http://localhost:3000/users

###
post http://localhost:3000/auth/register
Content-Type: application/json

{
    "user_id": 3,
    "firstName": "test",
    "lastName": "user",
    "admin": false,
    "password": "password"
}

###
post http://localhost:3000/auth/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjMxMDMzODIyLCJleHAiOjE2MzEwMzQ3MjJ9.1qvm9z_OpZMOcsJFWSFtmObKU7NaMlZXHpYtjxg6eqk
Content-Type: application/json

{
    "user_id": 3,
    "firstName": "test",
    "lastName": "user",
    "admin": false,
    "password": "password"
}

###
post http://localhost:3000/auth/login
Content-Type: application/json

{
    "user_id" : 1,
    "password" : "password"
}

###
delete http://localhost:3000/auth/logout

###
post http://localhost:3000/auth/token

###
get http://localhost:3000/admin

###
get http://localhost:3000/users/3

###
get http://localhost:3000/sales/1

###
delete http://localhost:3000/sales/1

###
get http://localhost:3000/inventory/00000


###
get http://localhost:3000/users


###
get http://localhost:3000/sales


###
get http://localhost:3000/inventory


