get http://localhost:3000/users

###
post http://localhost:3000/auth/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjMxMDMzODIyLCJleHAiOjE2MzEwMzQ3MjJ9.1qvm9z_OpZMOcsJFWSFtmObKU7NaMlZXHpYtjxg6eqk
Content-Type: application/json

{
    "user_id": 3,
    "firstName": "test",
    "lastName": "user",
    "admin": false,
    "password": "password"
}

###
post http://localhost:3000/auth/login
Content-Type: application/json

{
    "user_id" : 1,
    "password" : "password"
}

###
post http://localhost:3000/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjMxMDMzNDAyfQ.Wh84g3rMt348QQ8K5GCe-n0Wrai42IRvFJhYjcJjQ-s"
}

###
get http://localhost:3000/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTYzMTAzMzg0MiwiZXhwIjoxNjMxMDM0NzQyfQ.hpr0uCw-lsrAY-28bYDyYVf4IqT_C4FthHY8zkyuloE

###
get http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTYzMTAzMzg0MiwiZXhwIjoxNjMxMDM0NzQyfQ.hpr0uCw-lsrAY-28bYDyYVf4IqT_C4FthHY8zkyuloE

###
get http://localhost:3000/sales
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTYzMTAzMzg0MiwiZXhwIjoxNjMxMDM0NzQyfQ.hpr0uCw-lsrAY-28bYDyYVf4IqT_C4FthHY8zkyuloE

###
get http://localhost:3000/inventory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTYzMTAzMzg0MiwiZXhwIjoxNjMxMDM0NzQyfQ.hpr0uCw-lsrAY-28bYDyYVf4IqT_C4FthHY8zkyuloE

